#include "BIT_Math.h"
#include "Std_Types.h"
#include "NVIC_ppconfig.h"
#include "NVIC_interface.h"



const NVIC_Config_Type NVIC_Configurition[78] = {
		{INT_GPIOA , DISABLED , 1 } , {INT_GPIOB , DISABLED , 4 } , {INT_GPIOC , DISABLED , 4 } ,
		{INT_GPIOD , DISABLED , 4 } , {INT_GPIOE , DISABLED , 5 } , {INT_UART0 , DISABLED , 4 } ,
		{INT_UART1 , DISABLED , 0 } , {INT_SSI0 , DISABLED , 0 } , {INT_I2C0 , DISABLED , 0 } ,
		{INT_PWM0_FAULT , DISABLED , 0 } , {INT_PWM0_GEN0 , DISABLED , 0 } , {INT_PWM0_GEN1 , DISABLED , 0 } ,
		{INT_PWM0_GEN2 , DISABLED , 0 } , {INT_QEI0 , DISABLED , 0 } , {INT_ADC0_SEQ0 , DISABLED , 0 } ,
		{INT_ADC0_SEQ1 , DISABLED , 0 } , {INT_ADC0_SEQ2 , DISABLED , 0 } , {INT_ADC0_SEQ3 , DISABLED , 0 } ,
		{INT_WDT , DISABLED , 0 } , {INT_TIMER0A , DISABLED , 0 } , {INT_TIMER0B , DISABLED , 0 } ,
		{INT_TIMER1A , DISABLED , 0 } , {INT_TIMER1B , DISABLED , 0 } , {INT_TIMER2A , DISABLED , 0 } ,
		{INT_TIMER2B , DISABLED , 0 } , {INT_COMP0 , DISABLED , 0 } , {INT_COMP1 , DISABLED , 0 } ,
		{INT_SYSCTL , ENABLED , 0 } , {INT_FLASH , DISABLED , 0 } , {INT_GPIOF , DISABLED , 0 } ,
		{INT_UART2 , DISABLED , 0 } , {INT_SSI1 , DISABLED , 0 } , {INT_TIMER3A , DISABLED , 0 } ,
		{INT_TIMER3B , DISABLED , 0 } , {INT_I2C13 , DISABLED , 0 } , {INT_QEI1 , DISABLED , 0 } ,
		{INT_CAN0 , DISABLED , 0 } , {INT_CAN1 , DISABLED , 0 } , {INT_HIBERNATE , DISABLED , 0 } ,
		{INT_USB , DISABLED , 0 } , {INT_PWM0_GEN3 , DISABLED , 0 } , {INT_UDMA , DISABLED , 0 } ,
		{INT_UDMAERR , DISABLED , 0 } , {INT_ADC1_SEQ0 , DISABLED , 0 } , {INT_ADC1_SEQ1 , DISABLED , 0 } ,
		{INT_ADC1_SEQ2 , DISABLED , 0 } , {INT_ADC1_SEQ3 , DISABLED , 0 } , {INT_SSI2 , DISABLED , 0 } ,
		{INT_SSI3 , DISABLED , 0 } , {INT_UART3 , DISABLED , 0 } , {INT_UART4, DISABLED , 0 } ,
		{INT_UART5 , DISABLED , 0 } , {INT_UART6 , DISABLED , 0 } , {INT_UART7 , DISABLED , 0 } ,
		{INT_I2C2 , DISABLED , 0 } , {INT_I2C3 , DISABLED , 0 } , {INT_TIMER4A , DISABLED , 0 } ,
		{INT_TIMER4B , DISABLED , 0 } , {INT_TIMER5A , DISABLED , 0 } , {INT_TIMER5B , DISABLED , 0 } ,
		{INT_WTIMER0A , DISABLED , 0 } , {INT_WTIMER0B , DISABLED , 0 } , {INT_WTIMER1A , DISABLED , 0 } ,
		{INT_WTIMER1B , DISABLED , 0 } , {INT_WTIMER2A , DISABLED , 0 } , {INT_WTIMER2B , DISABLED , 0 } ,
		{INT_WTIMER3A , DISABLED , 0 } , {INT_WTIMER3B , DISABLED , 0 } , {INT_WTIMER4A , DISABLED , 0 } ,
		{INT_WTIMER4B , DISABLED , 0 } , {INT_WTIMER5A , DISABLED , 0 } , {INT_WTIMER5B , DISABLED , 0 } ,
		{INT_SYSEXC , DISABLED , 0 } , {INT_PWM1_GEN0 , DISABLED , 0 } , {INT_PWM1_GEN1 , DISABLED , 0 } ,
		{INT_PWM1_GEN2 , DISABLED , 0 } , {INT_PWM1_GEN3, DISABLED , 0 } , {INT_PWM1_FAULT , DISABLED , 0 } 
	
};
